export enum Routes {
  Root = "/",
  AppRoot = "/app",
  Home = "/app/home",
  Notes = "/app/notes",
  Scan = "/app/scan",
  Chats = "/app/chats",
  Chat = "/chat/:roomUid",
  Profile = "/app/profile",
  Tags = "/app/tags",
  EditTag = "/tags/:tagUid",
  Login = "/login",
  Register = "/register",
  Settings = "/settings",
  Tag = "/tag/:tagUid",
  EditNote = "/edit-note/:noteUid",
}
